### ISSUE TITLE
Blatt08 BinomialHeapTest erwartet falsche Größe des Heaps

### ISSUE THREAD

**Issue by Khalphion** [Code-Connect/TUM_Homework#11]
https://github.com/Code-Connect/TUM_Homework/blob/master/src/gad17/blatt08/BinomialHeapTest.java

`insert(0, 1, 2, 3, 4, 5, 6);` erzeugt einen Heap der Größe 3.

`deleteMin0_givenRanks0To3_givenHeapSize4_thenHeapSize3()` (Zeile 175) erwartet 3 nach Entfernen des Minimums, jedoch ergibt sich nach dem Merge die Größe 2?

![image](https://user-images.githubusercontent.com/10117554/27769236-0535ee40-5f26-11e7-8db7-966a0b14aa2f.png)

**Comment by Gott50** [comment]
Has bin fixed
